### ISSUE TITLE
Wiki Page - The Basic Game Loop - Link 404 ref

### ISSUE THREAD

**Issue by ShadowMarker789** [microsoft/DirectXTK12#114]
Wiki Page 

https://github.com/microsoft/DirectXTK12/wiki/The-basic-game-loop 

Setup Section, highlighted text ` VS 2017/2019/2022` 

Points to: 

https://github.com/walbourn/directx-vs-templates/raw/master/VSIX/Direct3DUWPGame.vsix 

Which 404s. 

Can we update the Wiki and point that link to a place that has the vsix? Would it be unwise to include a copy of the vsix in this project's codebase?

**Comment by walbourn** [comment]
Thanks for the heads-up. I switched all my github projects from master-to-main lately. I'll check the various wikis.

**Comment by walbourn** [comment]
Should be fixed now.

Thanks again!
