### ISSUE TITLE
Are d3d12sdklayers.dll symbols files available somewhere?

### ISSUE THREAD

**Issue by ms-RistoRK** [microsoft/DirectXTK12#124]
Hello, I'm developing a DirectX 12 app and I would like to use directx 12 symbols files for a better understanding while debugging.  So far all I get is this:

![image](https://user-images.githubusercontent.com/84108471/162492288-df2ee157-9af1-4949-a406-0785ecfa172c.png)

Can anyone please point me to where to symbols files are located (server/repo/path)?

Thx in advance, cheers.

Risto

**Comment by walbourn** [comment]
The Microsoft Symbol Server provides these, although not necessarily if you are running Windows Insider builds.

https://docs.microsoft.com/en-us/windows/win32/dxtecharts/debugging-with-symbols#using-the-microsoft-symbol-server
