### ISSUE TITLE
GenerateMips is causing TDR

### ISSUE THREAD

**Issue by venki-thiyag** [microsoft/DirectXTK12#132]
When using GenerateMips API, driver is resulting in TDR. Not sure of what is actually causing this problem.

Debug layers were enabled, following is the output which was received:

`D3D12 ERROR: ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_DEVICE_HUNG: The Device took an unreasonable amount of time to execute its commands, or the hardware crashed/hung. As a result, the TDR (Timeout Detection and Recovery) mechanism has been triggered. The current Device Context was executing commands when the hang occurred. The application may want to respawn and fallback to less aggressive use of the display hardware). [ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]
`

Any idea on how to proceed further?

**Comment by venki-thiyag** [comment]
To provide more details:
1) Format is DXGI_FORMAT_R8G8B8A8_UNORM
2) Image size is 640x360
3) Number of mips to be generated is 4
4) TypedUAVLoadAdditionalFormats is supported and StandardSwizzle64KBSupported is not supported

Sometime mipmap generation works and sometimes it doesn't

**Comment by walbourn** [comment]
What device are you using?

**Comment by venki-thiyag** [comment]
Intel(R) UHD Graphics

**Comment by walbourn** [comment]
Sorry, the attachment is missing.

It's likely a driver bug, but you could try ``D3D11_CREATE_DEVICE_DISABLE_GPU_TIMEOUT``.

**Comment by venki-thiyag** [comment]
Added D3D12_COMMAND_QUEUE_FLAG_DISABLE_GPU_TIMEOUT, since all processing is happening using D3D12.
With this change, MipMap generation is working, also I had to wait for execution completion after ExecuteCommandLists API is called.

Any concerns with respect to using the timeout flag?

**Comment by walbourn** [comment]
I suggest reporting this as a driver bug to Intel.
