### ISSUE TITLE
WICTextureLoader and DDSTextureLoader feature request

### ISSUE THREAD

**Issue by cpyburn** [microsoft/DirectXTK12#138]
DirectXTex returns ScratchImage that I can get properties of the image like size, width, etc.  The functions in DirectXTK do not.  I was really hoping when I saw these functions in DirectXTK that they would return the same information.  Can you add this in a future release?  It would be nice to have one less reference to another project when these functions exist. They do almost the exact same thing. They just dont return the data I need without going to modify DirectXTK source.

**Comment by walbourn** [comment]
*DirectXTex* is intended for tools usage where you often work with the image bitmap in memory with the CPU. If you are just wanting a way to load Direct3D resources from disk, the *DirectX Tool Kit* functions are best.  You can get the resource metadata directly from the Direct3D resource object using the ``ID3D12Resource::GetDesc`` method.

**Comment by walbourn** [comment]
See also the wiki [here](https://github.com/microsoft/DirectXTK12/wiki/DDSTextureLoader#debugging-texture-loading) and [here](https://github.com/microsoft/DirectXTK/wiki/WICTextureLoader#debugging-texture-loading).

**Comment by cpyburn** [comment]
Thanks, I try that.
