### ISSUE TITLE
"Basic Game Loop" from supplied Win32 template results in invalid window regions after window resize

### ISSUE THREAD

**Issue by jeremyong** [microsoft/DirectXTK12#177]
Before resize:

![image](https://github.com/microsoft/DirectXTK12/assets/250149/52d14265-317b-4994-b0b8-d1f49c249caa)

After resize:

![image](https://github.com/microsoft/DirectXTK12/assets/250149/9ae760d8-adb1-4a7b-a069-aec878139ca2)

Note the white border on the bottom and and right of the "after image."

I was running into this issue myself and decided to install the templates provided [here](https://github.com/Microsoft/DirectXTK12/wiki/The-basic-game-loop). Surprisingly, it seems the template suffers from the same issue as seen above. My current workaround is to shift the window 1 pixel back-and-forth immediately after resize, but obviously I would prefer to understand the root cause for why this happens. I am encountering this issue on Windows 10 Pro 22H2 (build 19045.3208). Any ideas would be appreciated, thanks!

**Comment by walbourn** [comment]
Is this a Win32 desktop application or a UWP?

**Comment by walbourn** [comment]
I am unable to reproduce this behavior on Windows 11 (22621) with any of the templates.

**Comment by jeremyong** [comment]
I saw a post on reddit with the same behavior reported recently (although my search skills seem to be failing me at the moment). I'm assuming this must be a Windows 10 issue because I can reproduce it immediately with the template linked and no modifications on my end. In my case I'm using Nvidia's 536.40 driver (not that I imagine this to be all that significant).

**Comment by walbourn** [comment]
I also am unable to reproduce this behavior on Windows 10 (19045) with any of the templates.

It *could* be a bug with some 'value-add' software thing on the system.

**Comment by jeremyong** [comment]
Hmm interesting, this is a relatively fresh developer machine, and I don't run "1337-gamer" software that I'm aware of, but I will double check, thanks for confirming.
