### ISSUE TITLE
Havok Animation System

### ISSUE THREAD

**Issue by aaronstackpole** [microsoft/DirectXTK12#197]
Around the time Microsoft bought this (Havok) was just about the time I was going to buy a license, when I went back, it was no longer available. Will this become part of DXTK or MiniEngine at some point? I noticed it was marked as (C) in Starfield, wondering if MS has plans to make it open source at some point. Animation system is difficult, and the only one left out there I'm aware of is Granny now.

**Comment by walbourn** [comment]
Havok is its own business. I don't have any plans to integrate existing middleware solutions directly into the toolkit project.
