### ISSUE TITLE
MSAAHelper file downloads download wrong version

### ISSUE THREAD

**Issue by IsaacDexter** [microsoft/DirectXTK12#200]
The documentation for the DirectXTK12 [MSAAHelper](https://github.com/microsoft/DirectXTK12/wiki/MSAAHelper) has links to download the DirectX12 versions of the files. 

When copy and pasting this does indeed link to the file, but when saving with ctrl-s, it instead downloads the DX11 versions.

Obviously this is a very small issue, and it's understandable it fell under the radar! But I thought I would at least let you know.

**Comment by walbourn** [comment]
Thank you for taking the time to report an issue. I don't actually understand what you mean by "Ctrl+S saves the DX11 versions". If you mean while in the linked page Ctrl+S in the browser saves the wrong version, then I'm not sure what is causing that. I don't see that behavior in my browser.
