### ISSUE TITLE
DirectXTK12 compiling errors on VS 2017 (v141) 

### ISSUE THREAD

**Issue by paspy** [Microsoft/DirectXTK12#21]
The project DirectXTK_Desktop_2017_Win10 won't compile and following errors appeared:

> 1>------ Build started: Project: DirectXTK12, Configuration: Debug x64 ------
1>pch.cpp
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\client.h(892): error C2187: syntax error: 'identifier' was unexpected here
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\client.h(900): error C2187: syntax error: 'identifier' was unexpected here
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\implements.h(629): error C2187: syntax error: ')' was unexpected here
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\implements.h(697): note: see reference to class template instantiation 'Microsoft::WRL::ChainInterfaces<I0,I1,I2,I3,I4,I5,I6,I7,I8,I9>' being compiled
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\implements.h(710): error C2187: syntax error: ')' was unexpected here
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\implements.h(781): note: see reference to class template instantiation 'Microsoft::WRL::ChainInterfaces<Microsoft::WRL::MixIn<Derived,MixInType,hasImplements>,I1,I2,I3,I4,I5,I6,I7,I8,I9>' being compiled
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\implements.h(955): error C2187: syntax error: ')' was unexpected here
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\implements.h(982): note: see reference to class template instantiation 'Microsoft::WRL::Details::ImplementsHelper<RuntimeClassFlagsT,Microsoft::WRL::Details::InterfaceList<Microsoft::WRL::ChainInterfaces<C0,C1,C2,C3,C4,C5,C6,C7,C8,C9>,I1>,doStrictCheck,false>' being compiled
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\implements.h(993): error C2187: syntax error: ')' was unexpected here
1>c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt\wrl\implements.h(1015): note: see reference to class template instantiation 'Microsoft::WRL::Details::ImplementsHelper<RuntimeClassFlagsT,Microsoft::WRL::Details::InterfaceList<Microsoft::WRL::ChainInterfaces<C0,C1,C2,C3,C4,C5,C6,C7,C8,C9>,Microsoft::WRL::Details::Nil>,doStrictCheck,false>' being compiled
1>Done building project "DirectXTK_Desktop_2017_Win10.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I am using latest Visual Studio Enterprise 2017 15.3.5

**Comment by walbourn** [comment]
This is already fixed in the [master](https://github.com/Microsoft/DirectXTK12/commit/83149fb670036d303ee62e174b4a620f138c7452) branch and will be included in a new release later this week.
