### ISSUE TITLE
Update the directxtk12 vcpkg package - only the release from dec2016 is available

### ISSUE THREAD

**Issue by jessey-git** [Microsoft/DirectXTK12#31]
With vcpkg getting more and more popular, it would be nice if the package there would be kept up to date and maintained.

It makes getting the bits and building them very simple for msft environments nowadays. Here's a listing of what's there today:
```
directxmesh          feb2018-eb751... DirectXMesh geometry processing library
directxtex           feb2018b         DirectXTex texture processing library
directxtk            feb2018          A collection of helper classes for writing DirectX 11.x code in C++.
directxtk12          dec2016          A collection of helper classes for writing DirectX 12 code in C++.
dx                   1.0.1            A modern C++ library for DirectX programming
```

**Comment by walbourn** [comment]
I don't maintain the vcpkg version. Please file the issue on the [vcpkg GitHub](https://github.com/Microsoft/vcpkg)

**Comment by walbourn** [comment]
BTW, they are all nov2020 at this point...
