### ISSUE TITLE
Use /permissive- for VS 2017 desktop projects

### ISSUE THREAD

**Issue by walbourn** [Microsoft/DirectXTK12#39]
There is a known issue with the Windows 10 SDK (17134) or earlier when using VS 2017 (15.8 update) and ``/permissive-``. This is fix in a future version of the Windows 10 SDK, so for now I've disabled the usage in [this commit](https://github.com/Microsoft/DirectXTK12/commit/26b106800d268fd2ac15ff5deb8e867a8bb72f32)

**Comment by walbourn** [comment]
Workaround remove when upgraded to the Windows 10 SDK (17763) in [this commit](https://github.com/Microsoft/DirectXTK12/commit/4670b2c2b30aea68710eba84f0721f1d785d42ce)

**Comment by oliver27b** [comment]
hey. i wasn't sure the best way to contact you; this revolves around maintenance for desktop projects.
i was following the tutorial https://github.com/microsoft/DirectXTK12/wiki/Adding-the-DirectX-Tool-Kit
using VS2019 with 10.0.18362.0 and was having problems; NuGet kinda blew up. so i followed the project to project references and it worked. when i started adding headers, some worked, others caused the build to come up with tons of errors. after prodding around a while, i found that if i added 
#include "dxgi.h"   to my pch.h, everything was happy :)  so the tutorial page above if you could let people know they need dxgi.h for some reason (maybe it's supposed to be a header in another file?). anyways i'm kinda new at this so excuse me if this is useless information.  thanks

**Comment by walbourn** [comment]
@oliver27b - Thanks for the report. It inspired me to add an explicit test to my [test suite](https://github.com/walbourn/directxtk12test/tree/master/HeaderTest) to validate that all my public headers were including all their dependencies and were 'warnings clean'.

I was indeed missing a few includes of dxgi headers in a few cases--all my previous tests, samles, and my tutorial templates include dxgi in the pch.h so hadn't noticed the issue before.

See [this commit](https://github.com/microsoft/DirectXTK12/commit/879df13bf769d5d234aba799e36a843f7f68dbf3) for the details of the fix.
