### ISSUE TITLE
Drawing Text

### ISSUE THREAD

**Issue by qcha0s** [Microsoft/DirectXTK12#4]
Loading a Bitmap Font section is missing:

std::unique_ptr<DirectX::SpriteFont>				m_font;

which needs to be added to Game.h

**Comment by qcha0s** [comment]
on further inspection it looks like you just added m_SpriteBatch as <SpriteBatch> where it should have been m_font as <SpriteFont>

**Comment by walbourn** [comment]
Fixed. Thanks!
