### ISSUE TITLE
D3D12_RENDER_PASS_DEPTH_STENCIL_DESC compare operator incorrectly checking StencilBeginningAccess against DepthBeginningAccess

### ISSUE THREAD

**Issue by JosephClampett** [Microsoft/DirectXTK12#51]
```cpp
if (a.cpuDescriptor.ptr != b.cpuDescriptor.ptr) return false;
if (!(a.DepthBeginningAccess == b.DepthBeginningAccess)) return false;
if (!(a.StencilBeginningAccess == b.DepthBeginningAccess)) return false;
if (!(a.DepthEndingAccess == b.DepthEndingAccess)) return false;
if (!(a.StencilEndingAccess == b.StencilEndingAccess)) return false;
```

On [line 2726](https://github.com/Microsoft/DirectXTK12/blob/16bb7adec908b548a468bd78a1a2d4ec9963a37a/Src/d3dx12.h#L2726) `StencilBeginningAccess` is incorrectly compared against `DepthBeginningAccess`.

**Comment by walbourn** [comment]
This is a bug with the ``d3dx12.h`` header which is actually hosted on [DirectX-Graphics-Samples](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Libraries/D3DX12/d3dx12.h). Looks like this was already fixed there, so I'll update my copies of it.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/Microsoft/DirectXTK12/commit/164b7957c0e746a2665e2d6339271c13b97d66a8)
