### ISSUE TITLE
FindPageForAlloc out of memory

### ISSUE THREAD

**Issue by MattFiler** [microsoft/DirectXTK12#55]
I'm currently trying to load a large SDKMesh and getting an out of memory throw in LinearAllocator's `FindPageForAlloc`. Is there any defined maximum size an SDKMesh can be, or is that something which is system dependant?

**Comment by MattFiler** [comment]
Finished in 3048fe4

**Comment by walbourn** [comment]
Please build and then run the [sdkmeshdump.cpp](https://raw.githubusercontent.com/wiki/Microsoft/DirectXMesh/sdkmeshdump.cpp) tool on your ``sdkmesh`` and post the results here so I can get a sense of the size of resources you need.

**Comment by MattFiler** [comment]
[Here's what I got back](https://pastebin.com/hNNBmEVz) for the model I'm having issues with.

**Comment by walbourn** [comment]
Also, are you calling ``GraphicsMemory::Commit`` each rendering frame? It's critical for the memory reclamation.

**Comment by MattFiler** [comment]
Yeah, I call it at the end of every render. I'm also utilising `GraphicsMemory:GarbageCollect` in-between loading models to try and help, but it doesn't seem to make much difference.

**Comment by MattFiler** [comment]
I'm calling `DeviceResources::WaitForGpu` before `GraphicsMemory::GarbageCollect` as the function states the GPU must be idled before using for best effects - is this correct?

**Comment by walbourn** [comment]
I think the question is what is your overall memory usage. The LinearAllocator used by GraphicsMemory grows the heap on-demand so it's not a fixed size. That said, it can't grow the heap larger than the amount of memory that your DirectX 12 driver supports for ``UPLOAD`` type heaps.

Are you loading a lot of models? Are you using ``LoadStaticBuffers`` to convert the ``UPLOAD`` VB/IB to ``DEFAULT``?

**Comment by MattFiler** [comment]
The issue occurs usually when switching between models - I use one large model for each of our environments. When changing environments I unload it, then load the next. They're all of a similar size to the dump I posted. The environments have a few other models loaded within them but they're all pretty small (~3K verts). When loading the models I do call `LoadStaticBuffers`, I guess this is correct?

**Comment by MattFiler** [comment]
Utilising `GraphicsMemory::GarbageCollect` after a call to `DeviceResources::WaitForGpu` following a reset of model resources did the trick for my runtime model swapping issue. To solve the initial "out of memory" loading issue I simply split my model into two SDKMESH files to load-in which seems to work fine.

This issue still applies to the original problem (loading the large SDKMESH and getting an "out of memory" issue), but my situation is fixed.

**Comment by walbourn** [comment]
Thanks. I'll keep an eye out for future problems.

I did add some more debugging output in [this commit](https://github.com/microsoft/DirectXTK12/commit/aca815faf2ed02bc810f6510e400abdde269fedb).

BTW, are you using 32-bit or 64-bit native?

**Comment by MattFiler** [comment]
Appreciate the help! I'm using 64-bit.
