### ISSUE TITLE
Creating A Grid

### ISSUE THREAD

**Issue by L-Fejes** [Microsoft/DirectXTK12#6]
In the Creating a Grid Section a call is made in the TODO section of the Game.cpp Render function that: m_effect->Apply(m_d3dContext.Get());.  This results in an error, because "m_d3dContext" is an undeclared identifier.

**Comment by qcha0s** [comment]
m_commandList.Get()

**Comment by walbourn** [comment]
Cut & paste error populating initial files from DX11. Thanks!
