### ISSUE TITLE
The vs2015 projects don't compile

### ISSUE THREAD

**Issue by sleepyspider1** [microsoft/DirectXTK12#60]
Are these auto generated?
The project type is set to build a static lib.
Does not link against the import lib d3d12.lib at all.
It doesn't know what winmain is either.

**Comment by walbourn** [comment]
It create a static lib. You are expected to use either project-to-project references from your own Win32 desktop app or use NuGet. See the [wiki](https://github.com/microsoft/DirectXTK12/wiki) and the [getting started tutorials](https://github.com/microsoft/DirectXTK12/wiki/Getting-Started).
