### ISSUE TITLE
Screenshot in dds with wrong colors

### ISSUE THREAD

**Issue by 0xD06C** [microsoft/DirectXTK12#65]
Hi everyone,

I use the function SaveDDSTextureToFile to save a screenshot but the image generated change de colors.

I don't know if I need other configuration. 

I added the file ScreenGrab.h and initialize it with the next code

	`#if (_WIN32_WINNT >= 0x0A00 /*_WIN32_WINNT_WIN10*/)
		Microsoft::WRL::Wrappers::RoInitializeWrapper initialize(RO_INIT_MULTITHREADED);
		if (FAILED(initialize))
			Log().Error("Error to initialize DirectX Tool Kit 12 - RO_INIT_MULTITHREADED");
	#else
		HRESULT hr = CoInitializeEx(nullptr, COINITBASE_MULTITHREADED);
		if (FAILED(hr))
			Log().Error("Error to initialize DirectX Tool Kit 12 - COINITBASE_MULTITHREADED");
	#endif`

It works but the colors are wrong.

Can you help me??

**Comment by walbourn** [comment]
What do you mean by 'wrong'?

Likely this is an issue of SRGB vs. Linear colors. See the [wiki](https://github.com/microsoft/DirectXTK/wiki/ScreenGrab#srgb-vs-linear-color-space)
