### ISSUE TITLE
Media Reader missing?

### ISSUE THREAD

**Issue by cpyburn** [microsoft/DirectXTK12#82]
Is Media Reader is missing in the XTK. or is there a new way to play MP3s?

**Comment by walbourn** [comment]
*DirectX Tool Kit* for Audio (included in both DX11 & DX12 versions), has a [SoundStreamInstance](https://github.com/microsoft/DirectXTK/wiki/SoundStreamInstance) class for doing streaming of PCM, ADPCM, and xWMA content from an XACT-style wavebank. For other kinds of compression, you need to implement your own solution or you can make use of [DynamicSoundEffectInstance](https://github.com/microsoft/DirectXTK/wiki/DynamicSoundEffectInstance)
