### ISSUE TITLE
WAV loop regions incorrectly read

### ISSUE THREAD

**Issue by pklima** [microsoft/DirectXTK12#83]
Hello, I noticed a bug in the reading of WAV loop regions in `WaveFindLoopInfo()`, specifically the region length is incorrectly set.

**Repro**
1. Obtain a WAV with loop points in it, e.g. `MinigunWindupAndFireLooped1.wav` from the [XNA Game Studios audio samples](https://github.com/SimonDarksideJ/XNAGameStudio/tree/archive/Samples/SoundLab/SoundLab/Audio/Guns/Minigun).
1. Replace `musicmono_adpcm.wav` in one of the [DirectXTK samples](https://github.com/walbourn/directxtk-samples) with the looped WAV above.
2. Run the sample in debug, observe an assert:
```
XAudio2: Loop region (75008-231711) does not end within the audio buffer (size 128640)
XAudio2: Invalid source buffer
```

The same issue is also present in the [DX11 version](https://github.com/microsoft/DirectXTK).

**Comment by pklima** [comment]
> The same issue is also present in the DX11 version.

I'm not quite sure what the best way to go about fixing this. I'm happy to provide a pull request into the other repo as well?

**Comment by walbourn** [comment]
Thanks for the fix. I'll be sure to propagate the fix elsewhere...

**Comment by walbourn** [comment]
* Fixed in both DX12 and [DX11](https://github.com/microsoft/DirectXTK/commit/8cfc8994cec85ee24402142d973dbe620b3f6f2a) versions
* Fixed in XAudio2 samples on [directx-sdk-samples](https://github.com/walbourn/directx-sdk-samples/commit/ab7ce2c3d7ec7a53c43cf481f4dec82177d24933).
