### ISSUE TITLE
Which Direct2D function can replace the GdipLoadImageFromStream function

### ISSUE THREAD

**Issue by laizewei** [microsoft/DirectXTK12#93]
Which Direct2D function can replace the GdipLoadImageFromStream function?

**Comment by walbourn** [comment]
This project is for *DirectX Tool Kit for DX12*. I can't really provide any help with Direct2D beyond pointing you to [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/direct2d/direct2d-portal) and the original [samples](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/multimedia/Direct2D).

You should look at other community support sites for help.
