### ISSUE TITLE
How do I load and draw an APNG file using Direct2D functions

### ISSUE THREAD

**Issue by laizewei** [microsoft/DirectXTK12#94]
How do I load and draw an APNG file using Direct2D functions

**Comment by walbourn** [comment]
I don't have any particular support for animated PNGs ([APNG](https://en.wikipedia.org/wiki/APNG)) in my libraries, and it's not a format supported by Windows Imaging Component (WIC) built-in codecs.

I do have support in [texassemble](https://github.com/microsoft/DirectXTex/wiki/Texassemble) to convert an animated GIF into a 2D texture array which you can then render as a 'flip-book'.
